server:
  port: 8765
spring:
  application:
    name: gateway-server

zuul:
  prefix: /api
  routes:
    employee:
      path: /employee/**
      serviceId: employee-service
    address:
      path: /address/**
      serviceId: address-service
    web:
      path: /web/**
      serviceId: web-mvc

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
