server:
  port: 8765
spring:
  application:
    name: gateway-server

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    employee:
      path: /employee/**
      serviceId: employee-service
    address:
      path: /address/**
      serviceId: address-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.100.96:8761/eureka/
    registerWithEureka: false
